name: Lint

on: [pull_request]

jobs:
  eslint:
    name: Run eslint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install yarn
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt-get update
          sudo apt-get install --no-install-recommends yarn

      - name: Install lerna
        run: npm i -g lerna --cache-min 999999999

      # ESLint and Prettier must be in `package.json`
      - name: Bootstrap lerna
        run: lerna bootstrap --concurrency=1 --mutex network 

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          eslint_extensions: ts,tsx
          prettier: true
